#!/usr/bin/env python3
"""Import textbook data from app/public/data/ JSON into D1.

Reads catalog.json + textbook-N/*.json, imports into D1.

用法：
  python3 scripts/import-to-d1.py              # 默认 --local
  python3 scripts/import-to-d1.py --local       # 导入本地 D1（直接操作 SQLite）
  python3 scripts/import-to-d1.py --remote      # 导入云端 D1（通过 wrangler）
  python3 scripts/import-to-d1.py --dry-run     # 仅生成 SQL 文件不执行
"""
from __future__ import annotations

import argparse
import glob
import json
import sqlite3
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "app" / "public" / "data"
SCHEMA = ROOT / "db" / "schema.sql"
APP_DIR = ROOT / "app"


def load(path: Path):
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def find_local_d1() -> Path | None:
    """Find the local D1 SQLite file."""
    pattern = str(APP_DIR / ".wrangler" / "state" / "v3" / "d1" / "miniflare-D1DatabaseObject" / "*.sqlite")
    files = glob.glob(pattern)
    # Filter out metadata.sqlite
    files = [f for f in files if "metadata" not in f]
    if files:
        return Path(files[0])
    return None


def generate_sql() -> tuple[str, int, int, int]:
    """Read JSON data and generate SQL INSERT statements."""
    catalog = load(DATA / "catalog.json")
    lines: list[str] = []

    # ── 1. 标记来源 ──
    lines.append("-- Auto-generated by import-to-d1.py")
    lines.append("")

    # ── 2. 清空教材表（全量替换） ──
    lines.append("DELETE FROM word_index;")
    lines.append("DELETE FROM textbook_families;")
    lines.append("DELETE FROM catalog_entries;")
    lines.append("")

    # ── 3. 插入 catalog_entries ──
    seen_keys: set[tuple[str, str]] = set()
    for entry in catalog:
        textbook = entry.get("textbook", "")
        fid = entry.get("id", "")
        key = (textbook, fid)
        if key in seen_keys:
            continue
        seen_keys.add(key)

        roots_json = json.dumps(entry.get("roots", []), ensure_ascii=False)
        lines.append(
            f"INSERT INTO catalog_entries "
            f"(id, textbook, file, chapter, chapter_order, title_zh, semantic_label, "
            f"meaning_en, meaning_zh, roots, word_count, source, legacy_id) VALUES ("
            f"{sql_str(fid)}, "
            f"{sql_str(textbook)}, "
            f"{sql_str(entry.get('file', ''))}, "
            f"{sql_str(entry.get('chapter'))}, "
            f"{entry.get('chapterOrder', 'NULL')}, "
            f"{sql_str(entry.get('titleZh'))}, "
            f"{sql_str(entry.get('semanticLabel'))}, "
            f"{sql_str(entry.get('meaningEn'))}, "
            f"{sql_str(entry.get('meaningZh'))}, "
            f"{sql_str(roots_json)}, "
            f"{entry.get('wordCount', 0)}, "
            f"{sql_str(entry.get('source'))}, "
            f"{sql_str(entry.get('legacyId'))}"
            f");"
        )
    lines.append("")

    # ── 4. 插入 textbook_families + word_index ──
    family_count = 0
    word_count = 0
    seen_families: set[tuple[str, str]] = set()

    for entry in catalog:
        textbook = entry.get("textbook", "")
        fid = entry.get("id", "")
        key = (textbook, fid)
        if key in seen_families:
            continue
        seen_families.add(key)

        family_path = DATA / textbook / entry.get("file", "")
        if not family_path.exists():
            print(f"  WARN: {family_path} not found, skipping", file=sys.stderr)
            continue

        family = load(family_path)
        family_json = json.dumps(family, ensure_ascii=False)

        lines.append(
            f"INSERT INTO textbook_families (textbook, family_id, data_json, updated_at) VALUES ("
            f"{sql_str(textbook)}, {sql_str(fid)}, {sql_str(family_json)}, 0);"
        )
        family_count += 1

        for w in family.get("words", []):
            lines.append(
                f"INSERT INTO word_index "
                f"(word, textbook, family_id, phonetic, pos, definition, mnemonic, root_hint, frequency) VALUES ("
                f"{sql_str(w.get('word', ''))}, "
                f"{sql_str(textbook)}, "
                f"{sql_str(fid)}, "
                f"{sql_str(w.get('phonetic'))}, "
                f"{sql_str(w.get('pos'))}, "
                f"{sql_str(w.get('definition'))}, "
                f"{sql_str(w.get('mnemonic'))}, "
                f"{sql_str(w.get('rootHint'))}, "
                f"{w.get('frequency', 'NULL')}"
                f");"
            )
            word_count += 1

    lines.append("")
    lines.append(f"-- Summary: {len(seen_keys)} catalog entries, {family_count} families, {word_count} words")

    return "\n".join(lines), len(seen_keys), family_count, word_count


def sql_str(v) -> str:
    """SQL-escape a value, returning NULL for None."""
    if v is None:
        return "NULL"
    if isinstance(v, (int, float)):
        return str(v)
    return "'" + str(v).replace("'", "''") + "'"


def import_local_direct() -> tuple[int, int, int]:
    """Import directly into local D1 SQLite file (bypasses wrangler CLI size limits)."""
    db_path = find_local_d1()
    if not db_path:
        print("ERROR: Local D1 database not found. Run schema first:", file=sys.stderr)
        print("  npx wrangler d1 execute rootgraph --local --file=../db/schema.sql", file=sys.stderr)
        sys.exit(1)

    print(f"Local D1: {db_path}")
    con = sqlite3.connect(db_path)

    # Clear tables
    con.execute("DELETE FROM word_index")
    con.execute("DELETE FROM textbook_families")
    con.execute("DELETE FROM catalog_entries")

    catalog = load(DATA / "catalog.json")
    catalog_count = 0
    family_count = 0
    word_count = 0
    seen_keys: set[tuple[str, str]] = set()
    seen_families: set[tuple[str, str]] = set()

    for entry in catalog:
        textbook = entry.get("textbook", "")
        fid = entry.get("id", "")
        key = (textbook, fid)
        if key in seen_keys:
            continue
        seen_keys.add(key)

        roots_json = json.dumps(entry.get("roots", []), ensure_ascii=False)
        con.execute(
            """INSERT INTO catalog_entries
               (id, textbook, file, chapter, chapter_order, title_zh, semantic_label,
                meaning_en, meaning_zh, roots, word_count, source, legacy_id)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (
                fid,
                textbook,
                entry.get("file", ""),
                entry.get("chapter"),
                entry.get("chapterOrder"),
                entry.get("titleZh"),
                entry.get("semanticLabel"),
                entry.get("meaningEn"),
                entry.get("meaningZh"),
                roots_json,
                entry.get("wordCount", 0),
                entry.get("source"),
                entry.get("legacyId"),
            ),
        )
        catalog_count += 1

    for entry in catalog:
        textbook = entry.get("textbook", "")
        fid = entry.get("id", "")
        key = (textbook, fid)
        if key in seen_families:
            continue
        seen_families.add(key)

        family_path = DATA / textbook / entry.get("file", "")
        if not family_path.exists():
            print(f"  WARN: {family_path} not found, skipping", file=sys.stderr)
            continue

        family = load(family_path)
        family_json = json.dumps(family, ensure_ascii=False)

        con.execute(
            "INSERT INTO textbook_families (textbook, family_id, data_json, updated_at) VALUES (?, ?, ?, 0)",
            (textbook, fid, family_json),
        )
        family_count += 1

        for w in family.get("words", []):
            con.execute(
                """INSERT INTO word_index
                   (word, textbook, family_id, phonetic, pos, definition, mnemonic, root_hint, frequency)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                (
                    w.get("word", ""),
                    textbook,
                    fid,
                    w.get("phonetic"),
                    w.get("pos"),
                    w.get("definition"),
                    w.get("mnemonic"),
                    w.get("rootHint"),
                    w.get("frequency"),
                ),
            )
            word_count += 1

    con.commit()
    con.close()
    return catalog_count, family_count, word_count


def build_payload() -> tuple[dict, int, int, int]:
    """Build JSON payload from textbook data."""
    catalog = load(DATA / "catalog.json")
    payload_catalog = []
    payload_families = []
    payload_words = []
    seen_keys: set[tuple[str, str]] = set()
    seen_families: set[tuple[str, str]] = set()

    for entry in catalog:
        textbook = entry.get("textbook", "")
        fid = entry.get("id", "")
        key = (textbook, fid)
        if key in seen_keys:
            continue
        seen_keys.add(key)

        payload_catalog.append({
            "id": fid,
            "textbook": textbook,
            "file": entry.get("file", ""),
            "chapter": entry.get("chapter"),
            "chapterOrder": entry.get("chapterOrder"),
            "titleZh": entry.get("titleZh"),
            "semanticLabel": entry.get("semanticLabel"),
            "meaningEn": entry.get("meaningEn"),
            "meaningZh": entry.get("meaningZh"),
            "roots": entry.get("roots", []),
            "wordCount": entry.get("wordCount", 0),
            "source": entry.get("source"),
            "legacyId": entry.get("legacyId"),
        })

    for entry in catalog:
        textbook = entry.get("textbook", "")
        fid = entry.get("id", "")
        key = (textbook, fid)
        if key in seen_families:
            continue
        seen_families.add(key)

        family_path = DATA / textbook / entry.get("file", "")
        if not family_path.exists():
            print(f"  WARN: {family_path} not found, skipping", file=sys.stderr)
            continue

        family = load(family_path)
        payload_families.append({
            "textbook": textbook,
            "familyId": fid,
            "dataJson": json.dumps(family, ensure_ascii=False),
        })

        for w in family.get("words", []):
            payload_words.append({
                "word": w.get("word", ""),
                "textbook": textbook,
                "familyId": fid,
                "phonetic": w.get("phonetic"),
                "pos": w.get("pos"),
                "definition": w.get("definition"),
                "mnemonic": w.get("mnemonic"),
                "rootHint": w.get("rootHint"),
                "frequency": w.get("frequency"),
            })

    return {
        "catalog": payload_catalog,
        "families": payload_families,
        "words": payload_words,
    }, len(seen_keys), len(payload_families), len(payload_words)


def import_remote() -> None:
    """Import to remote D1 via POST /api/db/import."""
    import os
    token = os.environ.get("SYNC_TOKEN", "rg_sync_2026_k8m3p7q2x9w4")
    url = "https://rootgraph.pages.dev/api/db/import"

    print("Building JSON payload from textbook data...")
    payload, n_catalog, n_families, n_words = build_payload()
    print(f"  {n_catalog} catalog entries, {n_families} families, {n_words} words")

    data = json.dumps(payload, ensure_ascii=False).encode("utf-8")
    print(f"  Payload size: {len(data) / 1024 / 1024:.1f} MB")

    print(f"\nImporting to remote D1 via {url}...")
    req = urllib.request.Request(
        url,
        data=data,
        headers={
            "Content-Type": "application/json",
            "Authorization": f"Bearer {token}",
            "User-Agent": "RootGraph-ImportScript/1.0",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=120) as resp:
            result = json.loads(resp.read().decode("utf-8"))
            print(f"Response: {result}")
            print("Done! Imported to remote D1 successfully.")
    except urllib.error.HTTPError as e:
        body = e.read().decode("utf-8", errors="replace")
        print(f"ERROR: HTTP {e.code}: {body}", file=sys.stderr)
        sys.exit(1)


def main() -> None:
    parser = argparse.ArgumentParser(description="Import textbook JSON data into D1")
    parser.add_argument("--local", action="store_true", default=True, help="Import to local D1 (default)")
    parser.add_argument("--remote", action="store_true", help="Import to remote (production) D1")
    parser.add_argument("--dry-run", action="store_true", help="Generate SQL file only, don't execute")
    args = parser.parse_args()

    if not (DATA / "catalog.json").exists():
        print(f"ERROR: {DATA / 'catalog.json'} not found", file=sys.stderr)
        sys.exit(1)

    if args.dry_run:
        print("Generating SQL from JSON data...")
        sql_content, n_catalog, n_families, n_words = generate_sql()
        sql_path = ROOT / "db" / "import-textbook-data.sql"
        sql_path.write_text(sql_content, encoding="utf-8")
        print(f"SQL file: {sql_path}")
        print(f"  {n_catalog} catalog entries, {n_families} families, {n_words} words")
        print("Dry run — SQL file generated, not executed.")
        return

    if args.remote:
        import_remote()
        return

    # Local mode: direct SQLite access
    print("Importing to local D1 (direct SQLite)...")
    n_catalog, n_families, n_words = import_local_direct()
    print(f"Done! Imported to local D1: {n_catalog} catalog, {n_families} families, {n_words} words")


if __name__ == "__main__":
    main()
